server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.254.1.13:3306/tax_db?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: root
    password: welcome
#    hikari:
#      poolName: DPMS-Hikari
#      maximum-pool-size: 10
#      max-lifetime: 1800000
#      auto-commit: false
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 250
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate

logging:
  register-shutdown-hook: false
  config: classpath:logback-loc.xml
  level:
    root: INFO
    com.kt.weather: INFO
    org.apache.http: INFO
    org.mybatis: WARN
