server:
#  port: 8080
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://tax-database.c1ttexowmmks.ap-northeast-2.rds.amazonaws.com:3306/tax?autoReconnection=true&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: tax_admin
    password: hli6363!
  datasource-second:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://tax-dbms.cjzouundkjlm.ap-northeast-2.rds.amazonaws.com:3306/finger_auto?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: root
    password: welcome123

logging:
  register-shutdown-hook: false
  config: classpath:logback-loc.xml
  level:
    root: INFO
    com.hanwha.tax: DEBUG
    org.apache.http: INFO
    org.mybatis: WARN

tax:
  licence: D:/dev/licence/P09510000000_IDS_01_PROD_AES_license.dat
