spring:
  profiles:
    active: local
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: pepega524832857240
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  application:
    name: 01

management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always


