server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.254.1.18:3306/tax_db2?autoReconnection=true&useSSL=false&allowMultiQueries=true
#    url: jdbc:mysql://172.30.1.15:3306/tax_db?autoReconnection=true&useSSL=false&allowMultiQueries=true
    username: root
    password: welcome
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate

logging:
  register-shutdown-hook: false
  config: classpath:logback-loc.xml
  level:
    root: INFO
    com.kt.weather: INFO
    org.apache.http: INFO
    org.mybatis: WARN

tax:
  licence: D:/dev/licence/P09510000000_IDS_01_PROD_AES_license.dat
