server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    showSql: true
    hibernate:
      ddl-auto: update

logging:
  register-shutdown-hook: false
  config: /home/tax/tax_api/config/logback-dev.xml
  level:
    root: INFO
    com.kt.weather: INFO
    org.apache.http: INFO
    org.mybatis: WARN